FORMAT: 1A
Host: https://wisetime.io

# WiseTime API
WiseTime API allows direct access to the time data created by the WiseTime platform.

## User [/api/user/{userId}]
A single User object with all its details

+ Parameters
    + userId (required, number, `1`) ... Numeric `userId` of the User to fetch the information for.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
